### ISSUE TITLE
Need your help!

### ISSUE THREAD

**Issue by quicklybly** [quicklybly/operating-systems-workshop#2]
Folks, can anyone send me this shitty reports. 
First person, who'll do it will be in this repository hall of fame!

**Comment by raiden-20** [comment]
10 ₽

**Comment by quicklybly** [comment]
where is your open source spirit?

**Comment by raiden-20** [comment]
100 ₽
or tipis answers

**Comment by quicklybly** [comment]
blackmail -> blacklist

**Comment by quicklybly** [comment]
tagger is my only friend

**Comment by raiden-20** [comment]
bullshit
